language: ruby
rvm:
  - "2.2.3"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/application.travis.yml config/application.yml
  - psql -c 'create database coursewareofthefuture_test;' -U postgres
  - psql -U postgres -q -d coursewareofthefuture_test -f db/structure.sql

script: 'CODECLIMATE_REPO_TOKEN=987608b798bb220f5268b66965c871090d90331328f3a4c7ae5a5b739ff6848c bundle exec rake'
